name: Release
on:
  release:
    types:
      - published

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        if: github.event.release.prerelease == false
        id: docker_build_and_push
        uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          tags: |
            ghcr.io/devfolioco/jessegpt:${{ github.event.release.tag_name }}
            ghcr.io/devfolioco/jessegpt:latest
          build-args: |
            NPM_TOKEN=${{ secrets.GPR_ACCESS_TOKEN }}
