install:
	uv sync
	uv pip install -e ./livekit-plugins-smallest --config-settings editable_mode=strict

dev:
	uv run -m voice_agent dev

start:
	uv run -m voice_agent start

download-files:
	uv run -m voice_agent download-files
